### ISSUE TITLE
Reply with Group Number and Class Section

### ISSUE THREAD

**Issue by ProfRojas** [sjkchang/vigilant-waffle#1]

**Comment by ProfRojas** [comment]
Also, just to verify that everyone created a GitHub account can you have all of your teammates post a message on this issue. They can just say hello.

**Comment by Vero-Guardado** [comment]
Hello everyone, team #4 from CMPE 131 Sec. 01

**Comment by shivshankar123** [comment]
Hello everyone, team #4 from CMPE 131 Sec. 01

**Comment by shivshankar123** [comment]
Hi, I am in team 4 and CMPE sec 01

**Comment by tuedolm** [comment]
Hi guys

**Comment by sjkchang** [comment]
Hello everyone, team #4 from CMPE 131 Sec. 01

**Comment by ProfRojas** [comment]
Thanks!
